### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by janji404** [HuHongYong/Mapbox-sprite-generation#1]
作者老哥，请问下这个工具在windows下如何使用呢

**Comment by HuHongYong** [comment]
查看这篇https://www.cnblogs.com/ATtuing/p/9273391.html，可以使用Microsoft Visual Studio打来编译源码，使用c#语言，也可以百度云下载源码和编译好的的文件，bin下面有个可执行exe，点击就能运行，不需要编译

**Comment by janji404** [comment]
thanks，可以使用了，非常感谢🙏



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 胡宏勇 <notifications@github.com&gt;
发送时间: 2020年9月28日 09:18
收件人: HuHongYong/Mapbox-sprite-generation <Mapbox-sprite-generation@noreply.github.com&gt;
抄送: hujiajie8002 <1185513671@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[HuHongYong/Mapbox-sprite-generation] 如何使用 (#1)





 
查看这篇https://www.cnblogs.com/ATtuing/p/9273391.html，可以使用Microsoft Visual Studio打来编译源码，使用c#语言，也可以百度云下载源码和编译好的的文件，bin下面有个可执行exe，点击就能运行，不需要编译
